import { VerbEntry, VerbDictionaryEntry } from "../../../../types";
// DO NOT MODIFY - GENERATED
export const entries: VerbEntry[] = [
  {
    entry: {
      ts: 1527812507,
      p: "بوتلل",
      f: "botlúl",
      e: "to take, bring, send (by transporting or leading - not by physically carrying)",
      r: 4,
      c: "v. trans.",
      ec: "take,takes,taking,took,taken",
      psp: "بیای",
      psf: "byaay",
      ssp: "بوځ",
      ssf: "bódz",
      noOo: true,
      separationAtP: 2,
      separationAtF: 2,
      a: 2,
      i: 2291,
      g: "botlul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527814038,
      p: "پاڅېدل",
      f: "paatsedúl",
      e: "to get up, rise, wake up",
      r: 4,
      c: "v. intrans.",
      ec: "get, gets, getting, got, gotten",
      ep: "up",
      shortIntrans: true,
      noOo: true,
      separationAtP: 2,
      separationAtF: 3,
      a: 3,
      i: 2757,
      g: "paatsedul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527817903,
      p: "پرانستل",
      f: "praanistúl",
      e: "to open; to undo; to initiate",
      r: 4,
      c: "v. trans.",
      psp: "پرانیز",
      psf: "praaneez",
      noOo: true,
      separationAtP: 3,
      separationAtF: 4,
      a: 3,
      i: 2969,
      g: "praanistul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1577389204616,
      p: "پرانیستل",
      f: "praaneestúl",
      e: "to open; to undo; to initiate",
      r: 4,
      c: "v. trans.",
      ec: "open",
      psp: "پرانیز",
      psf: "praaneez",
      noOo: true,
      separationAtP: 3,
      separationAtF: 4,
      a: 3,
      i: 2970,
      g: "praaneestul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527815190,
      p: "پرېښودل",
      f: "prexodúl",
      e: "to leave, abandon, forsake, let go, allow",
      r: 4,
      c: "v. trans.",
      ec: "abandon",
      psp: "پرېږد",
      psf: "preGd",
      noOo: true,
      separationAtP: 3,
      separationAtF: 3,
      a: 3,
      i: 3100,
      g: "prexodul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527815191,
      p: "پرېښول",
      f: "prexawúl",
      e: "to leave, abandon, forsake, let go, allow",
      r: 4,
      c: "v. trans.",
      psp: "پرېږد",
      psf: "preGd",
      noOo: true,
      separationAtP: 3,
      separationAtF: 3,
      a: 1,
      i: 3101,
      g: "prexawul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1577390597820,
      p: "پرېښوول",
      f: "prexowúl",
      e: "to leave, abandon, forsake, let go, allow",
      r: 4,
      c: "v. trans.",
      psp: "پرېږد",
      psf: "preGd",
      noOo: true,
      separationAtP: 3,
      separationAtF: 3,
      i: 3102,
      g: "prexowul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527817259,
      p: "پرېوتل",
      f: "prewatúl",
      e: "to fall, to lie down, to go down",
      r: 4,
      c: "v. intrans.",
      ec: "fall,falls,falling,fell,fallen",
      psp: "پرېوځ",
      psf: "prewudz",
      ssp: "پرېووځ",
      ssf: "prewÚoodz",
      tppp: "پرېوت, پرېواته",
      tppf: "preewot, prewaatu",
      prp: "پرېوتل",
      prf: "préwatul",
      noOo: true,
      separationAtP: 3,
      separationAtF: 3,
      diacExcept: true,
      a: 3,
      i: 3118,
      g: "prewatul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527815348,
      p: "تلل",
      f: "tlul",
      e: "to go",
      r: 4,
      c: "v. intrans.",
      ec: "go,goes,going,went,gone",
      psp: "ځ",
      psf: "dz",
      ssp: "لاړ ش",
      ssf: "láaR sh",
      prp: "لاړل",
      prf: "láaRul",
      separationAtP: 2,
      separationAtF: 3,
      a: 3,
      i: 4645,
      g: "tlul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527819674,
      p: "څملاستل",
      f: "tsumlaastúl",
      e: "to lie down",
      r: 4,
      c: "v. intrans.",
      ec: "lay,lays,lying,lay,layed",
      ep: "down",
      psp: "څمل",
      psf: "tsaml",
      noOo: true,
      separationAtP: 2,
      separationAtF: 4,
      a: 2,
      i: 6540,
      g: "tsumlaastul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1585228551150,
      p: "درتلل",
      f: "dartlúl",
      e: "to come (to you / second person)",
      r: 3,
      c: "v. intrans.",
      ec: "come,comes,coming,came,come",
      psp: "درځ",
      psf: "dardz",
      ssp: "درش",
      ssf: "dársh",
      tppp: "درغی",
      tppf: "darghay",
      prp: "درغلل",
      prf: "dárghlul",
      pprtp: "درغلی",
      pprtf: "darghúlay",
      noOo: true,
      separationAtP: 2,
      separationAtF: 3,
      a: 2,
      i: 7822,
      g: "dartlul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527815216,
      p: "راتلل",
      f: "raatlúl",
      e: "to come",
      r: 4,
      c: "v. intrans.",
      ec: "come,comes,coming,came,come",
      psp: "راځ",
      psf: "raadz",
      ssp: "راش",
      ssf: "ráash",
      tppp: "راغی",
      tppf: "ráaghay",
      prp: "راغلل",
      prf: "ráaghlul",
      pprtp: "راغلی",
      pprtf: "raaghúlay",
      noOo: true,
      separationAtP: 2,
      separationAtF: 3,
      a: 3,
      i: 8564,
      g: "raatlul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527817023,
      p: "راکښل",
      f: "raakxúl",
      e: "to take out, pull out, extract, drag, tug, pull towards, draw out, draw",
      r: 3,
      c: "v. trans.",
      psp: "راکاږ",
      psf: "raakaaG",
      noOo: true,
      separationAtP: 2,
      separationAtF: 3,
      a: 2,
      i: 8619,
      g: "raakxul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1708115597300,
      p: "رانیسل",
      f: "raaneesúl",
      e: "to catch",
      c: "v. trans.",
      ec: "catch,catches,catching,caught",
      ssp: "راونیس",
      ssf: "raa`óonees",
      prp: "راونیسل",
      prf: "raa`óoneesul",
      separationAtP: 3,
      separationAtF: 5,
      a: 3,
      i: 8640,
      g: "raaneesul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527815214,
      p: "راوړل",
      f: "raawRúl",
      e: "to bring, deliver (by physically carrying something, someone)",
      r: 4,
      c: "v. trans.",
      ec: "bring,brings,bringing,brought,brought",
      tppp: "راووړ",
      tppf: "raawoR",
      noOo: true,
      separationAtP: 2,
      separationAtF: 3,
      a: 3,
      i: 8651,
      g: "raawRul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527819827,
      p: "راوستل",
      f: "raawustúl, raawistúl",
      e: "to bring, deliver (by transporting or leading something/someone) obtain, extract",
      r: 3,
      c: "v. trans.",
      ec: "bring,brings,bringing,brought,brought",
      psp: "راول",
      psf: "raawul",
      noOo: true,
      separationAtP: 2,
      separationAtF: 3,
      a: 3,
      i: 8652,
      g: "raawustul,raawistul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527817577,
      p: "کښېښودل",
      f: "kxexodúl",
      e: "to put, to put down, to set in place",
      r: 3,
      c: "v. trans.",
      ec: "put,puts,putting,put",
      psp: "ږد",
      psf: "Gd",
      ssp: "کښېږد",
      ssf: "kxéGd",
      noOo: true,
      separationAtP: 3,
      separationAtF: 3,
      a: 2,
      i: 13152,
      g: "kxexodul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527812758,
      p: "کښېناستل",
      f: "kxenaastul",
      e: "to sit down, to have a seat",
      r: 4,
      c: "v. intrans.",
      ec: "sit,sits,sitting,sat",
      ep: "down",
      psp: "کښېن",
      psf: "kxen",
      noOo: true,
      separationAtP: 3,
      separationAtF: 3,
      i: 13156,
      g: "kxenaastul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527812284,
      p: "کېښودل",
      f: "kexodúl",
      e: "to put, to put down, to set in place",
      r: 4,
      c: "v. trans.",
      ec: "put,puts,putting,put,put",
      psp: "ږد",
      psf: "Gd",
      ssp: "کېږد",
      ssf: "kéGd",
      noOo: true,
      separationAtP: 2,
      separationAtF: 2,
      a: 3,
      i: 13671,
      g: "kexodul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527812759,
      p: "کېناستل",
      f: "kenaastúl",
      e: "to sit down, to have a seat",
      r: 4,
      c: "v. intrans.",
      ec: "sit,sits,sitting,sat",
      ep: "down",
      psp: "کېن",
      psf: "ken",
      noOo: true,
      separationAtP: 2,
      separationAtF: 2,
      a: 3,
      i: 13688,
      g: "kenaastul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1566477926101,
      p: "کېوتل",
      f: "kewatúl",
      e: "to get into, to come out, find oneself in, to fall into, to burst into or penetrate",
      r: 3,
      c: "v. intrans.",
      psp: "کېوځ",
      psf: "keoodz",
      noOo: true,
      separationAtP: 2,
      separationAtF: 2,
      a: 2,
      i: 13703,
      g: "kewatul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1585228579997,
      p: "ورتلل",
      f: "wartlúl",
      e: "to come / go over to (third person or place)",
      r: 4,
      c: "v. intrans.",
      ec: "come,comes,coming,came,come",
      psp: "ورځ",
      psf: "wardz",
      ssp: "ورش",
      ssf: "wársh",
      tppp: "ورغی",
      tppf: "warghay",
      prp: "ورغلل",
      prf: "wárghlul",
      pprtp: "ورغلی",
      pprtf: "warghúlay",
      noOo: true,
      separationAtP: 2,
      separationAtF: 3,
      a: 2,
      i: 18137,
      g: "wartlul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1594217649053,
      p: "وروستل",
      f: "warwustúl",
      e: "to bring, deliver (animate objects), obtain, extract",
      r: 3,
      c: "v. trans.",
      separationAtP: 2,
      separationAtF: 3,
      i: 18194,
      g: "warwustul",
    } as VerbDictionaryEntry,
  },
  {
    entry: {
      ts: 1527816865,
      p: "وړل",
      f: "wuRúl, oRúl, wRúl",
      e: "to take, carry, bear, move (by physically carrying); to win, earn (subjunctive یوسي - yósee or ویسي - wéesee, simple past یو یې وړلو - yo ye wRulo)",
      r: 3,
      c: "v. trans.",
      ec: "take,takes,taking,took,taken",
      ssp: "یوس",
      ssf: "yos",
      prp: "یوړل",
      prf: "yóRul",
      noOo: true,
      separationAtP: 2,
      separationAtF: 2,
      diacExcept: true,
      a: 3,
      i: 18240,
      g: "wuRul,oRul,wRul",
    } as VerbDictionaryEntry,
  },
];
