const expected = [
  {
    info: {
      aspect: "imperfective",
      base: "stem",
      imperative: true,
      type: "verb",
      verb: {
        entry: {
          c: "v. trans.",
          e: "to accept, to believe",
          ec: "accepting",
          f: "manul",
          g: "manul",
          p: "منل",
          r: 4,
          tppf: "maanu",
          tppp: "مانه",
          ts: 1527815085,
        },
      },
    },
    person: 2,
    type: "VB",
  },
  {
    info: {
      aspect: "imperfective",
      base: "stem",
      imperative: true,
      type: "verb",
      verb: {
        entry: {
          c: "v. trans.",
          e: "to accept, to believe",
          ec: "accepting",
          f: "manul",
          g: "manul",
          p: "منل",
          r: 4,
          tppf: "maanu",
          tppp: "مانه",
          ts: 1527815085,
        },
      },
    },
    person: 3,
    type: "VB",
  },
  {
    info: {
      aspect: "perfective",
      base: "stem",
      imperative: true,
      type: "verb",
      verb: {
        entry: {
          c: "v. trans.",
          e: "to accept, to believe",
          ec: "accepting",
          f: "manul",
          g: "manul",
          p: "منل",
          r: 4,
          tppf: "maanu",
          tppp: "مانه",
          ts: 1527815085,
        },
      },
    },
    person: 2,
    type: "VB",
  },
  {
    info: {
      aspect: "perfective",
      base: "stem",
      imperative: true,
      type: "verb",
      verb: {
        entry: {
          c: "v. trans.",
          e: "to accept, to believe",
          ec: "accepting",
          f: "manul",
          g: "manul",
          p: "منل",
          r: 4,
          tppf: "maanu",
          tppp: "مانه",
          ts: 1527815085,
        },
      },
    },
    person: 3,
    type: "VB",
  },
];

const received = [
  {
    info: {
      aspect: "imperfective",
      base: "stem",
      imperative: true,
      type: "verb",
      verb: {
        entry: {
          c: "v. trans.",
          e: "to accept, to believe",
          ec: "accepting",
          f: "manul",
          g: "manul",
          p: "منل",
          r: 4,
          tppf: "maanu",
          tppp: "مانه",
          ts: 1527815085,
        },
      },
    },
    person: 2,
    type: "VB",
  },
  {
    info: {
      aspect: "imperfective",
      base: "stem",
      imperative: true,
      type: "verb",
      verb: {
        entry: {
          c: "v. trans.",
          e: "to accept, to believe",
          ec: "accepting",
          f: "manul",
          g: "manul",
          p: "منل",
          r: 4,
          tppf: "maanu",
          tppp: "مانه",
          ts: 1527815085,
        },
      },
    },
    person: 3,
    type: "VB",
  },
  {
    info: {
      aspect: "perfective",
      base: "stem",
      imperative: true,
      type: "verb",
      verb: {
        entry: {
          c: "v. trans.",
          e: "to accept, to believe",
          ec: "accepting",
          f: "manul",
          g: "manul",
          p: "منل",
          r: 4,
          tppf: "maanu",
          tppp: "مانه",
          ts: 1527815085,
        },
      },
    },
    person: 2,
    type: "VB",
  },
  {
    info: {
      aspect: "perfective",
      base: "stem",
      imperative: true,
      type: "verb",
      verb: {
        entry: {
          c: "v. trans.",
          e: "to accept, to believe",
          ec: "accepting",
          f: "manul",
          g: "manul",
          p: "منل",
          r: 4,
          tppf: "maanu",
          tppp: "مانه",
          ts: 1527815085,
        },
      },
    },
    person: 3,
    type: "VB",
  },
  {
    info: {
      aspect: "imperfective",
      base: "root",
      type: "verb",
      verb: {
        entry: {
          c: "v. trans.",
          e: "to accept, to believe",
          ec: "accepting",
          f: "manul",
          g: "manul",
          p: "منل",
          r: 4,
          tppf: "maanu",
          tppp: "مانه",
          ts: 1527815085,
        },
      },
    },
    person: 5,
    type: "VB",
  },
  {
    info: {
      aspect: "perfective",
      base: "root",
      type: "verb",
      verb: {
        entry: {
          c: "v. trans.",
          e: "to accept, to believe",
          ec: "accepting",
          f: "manul",
          g: "manul",
          p: "منل",
          r: 4,
          tppf: "maanu",
          tppp: "مانه",
          ts: 1527815085,
        },
      },
    },
    person: 5,
    type: "VB",
  },
];
