const b = [
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            e: "to come",
            ec: "come,comes,coming,came,come",
            f: "raatlúl",
            g: "raatlul",
            noOo: true,
            p: "راتلل",
            pprtf: "raaghúlay",
            pprtp: "راغلی",
            prf: "ráaghlul",
            prp: "راغلل",
            psf: "raadz",
            psp: "راځ",
            r: 4,
            separationAtF: 3,
            separationAtP: 2,
            ssf: "ráash",
            ssp: "راش",
            tppf: "ráaghay",
            tppp: "راغی",
            ts: 1527815216,
          },
        },
      },
      person: 4,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            e: "to come",
            ec: "come,comes,coming,came,come",
            f: "raatlúl",
            g: "raatlul",
            noOo: true,
            p: "راتلل",
            pprtf: "raaghúlay",
            pprtp: "راغلی",
            prf: "ráaghlul",
            prp: "راغلل",
            psf: "raadz",
            psp: "راځ",
            r: 4,
            separationAtF: 3,
            separationAtP: 2,
            ssf: "ráash",
            ssp: "راش",
            tppf: "ráaghay",
            tppp: "راغی",
            ts: 1527815216,
          },
        },
      },
      person: 5,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            e: "to come",
            ec: "come,comes,coming,came,come",
            f: "raatlúl",
            g: "raatlul",
            noOo: true,
            p: "راتلل",
            pprtf: "raaghúlay",
            pprtp: "راغلی",
            prf: "ráaghlul",
            prp: "راغلل",
            psf: "raadz",
            psp: "راځ",
            r: 4,
            separationAtF: 3,
            separationAtP: 2,
            ssf: "ráash",
            ssp: "راش",
            tppf: "ráaghay",
            tppp: "راغی",
            ts: 1527815216,
          },
        },
      },
      person: 10,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            e: "to come",
            ec: "come,comes,coming,came,come",
            f: "raatlúl",
            g: "raatlul",
            noOo: true,
            p: "راتلل",
            pprtf: "raaghúlay",
            pprtp: "راغلی",
            prf: "ráaghlul",
            prp: "راغلل",
            psf: "raadz",
            psp: "راځ",
            r: 4,
            separationAtF: 3,
            separationAtP: 2,
            ssf: "ráash",
            ssp: "راش",
            tppf: "ráaghay",
            tppp: "راغی",
            ts: 1527815216,
          },
        },
      },
      person: 11,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            e: "to become _____",
            ec: "become",
            f: "kedul",
            g: "kedul",
            noOo: true,
            p: "کېدل",
            pprtf: "shúway",
            pprtp: "شوی",
            prf: "shwul",
            prp: "شول",
            r: 2,
            ssf: "sh",
            ssp: "ش",
            ts: 1581086654898,
          },
        },
      },
      person: 4,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            e: "to become _____",
            ec: "become",
            f: "kedul",
            g: "kedul",
            noOo: true,
            p: "کېدل",
            pprtf: "shúway",
            pprtp: "شوی",
            prf: "shwul",
            prp: "شول",
            r: 2,
            ssf: "sh",
            ssp: "ش",
            ts: 1581086654898,
          },
        },
      },
      person: 5,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            e: "to become _____",
            ec: "become",
            f: "kedul",
            g: "kedul",
            noOo: true,
            p: "کېدل",
            pprtf: "shúway",
            pprtp: "شوی",
            prf: "shwul",
            prp: "شول",
            r: 2,
            ssf: "sh",
            ssp: "ش",
            ts: 1581086654898,
          },
        },
      },
      person: 10,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            e: "to become _____",
            ec: "become",
            f: "kedul",
            g: "kedul",
            noOo: true,
            p: "کېدل",
            pprtf: "shúway",
            pprtp: "شوی",
            prf: "shwul",
            prp: "شول",
            r: 2,
            ssf: "sh",
            ssp: "ش",
            ts: 1581086654898,
          },
        },
      },
      person: 11,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            diacExcept: true,
            e: "to happen, occur",
            ec: "happen",
            f: "kedul",
            g: "kedul",
            p: "کېدل",
            pprtf: "shúway",
            pprtp: "شوی",
            prf: "óoshwul",
            prp: "وشول",
            r: 2,
            separationAtF: 2,
            separationAtP: 1,
            ssf: "óosh",
            ssp: "وش",
            ts: 1527812754,
          },
        },
      },
      person: 4,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            diacExcept: true,
            e: "to happen, occur",
            ec: "happen",
            f: "kedul",
            g: "kedul",
            p: "کېدل",
            pprtf: "shúway",
            pprtp: "شوی",
            prf: "óoshwul",
            prp: "وشول",
            r: 2,
            separationAtF: 2,
            separationAtP: 1,
            ssf: "óosh",
            ssp: "وش",
            ts: 1527812754,
          },
        },
      },
      person: 5,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            diacExcept: true,
            e: "to happen, occur",
            ec: "happen",
            f: "kedul",
            g: "kedul",
            p: "کېدل",
            pprtf: "shúway",
            pprtp: "شوی",
            prf: "óoshwul",
            prp: "وشول",
            r: 2,
            separationAtF: 2,
            separationAtP: 1,
            ssf: "óosh",
            ssp: "وش",
            ts: 1527812754,
          },
        },
      },
      person: 10,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            diacExcept: true,
            e: "to happen, occur",
            ec: "happen",
            f: "kedul",
            g: "kedul",
            p: "کېدل",
            pprtf: "shúway",
            pprtp: "شوی",
            prf: "óoshwul",
            prp: "وشول",
            r: 2,
            separationAtF: 2,
            separationAtP: 1,
            ssf: "óosh",
            ssp: "وش",
            ts: 1527812754,
          },
        },
      },
      person: 11,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            e: "to come / go over to (third person or place)",
            ec: "come,comes,coming,came,come",
            f: "wărtlul",
            g: "wartlul",
            noOo: true,
            p: "ورتلل",
            pprtf: "wărghúlay",
            pprtp: "ورغلی",
            prf: "wárghlul",
            prp: "ورغلل",
            psf: "wărdz",
            psp: "ورځ",
            r: 4,
            separationAtF: 3,
            separationAtP: 2,
            ssf: "wársh",
            ssp: "ورش",
            tppf: "wărghay",
            tppp: "ورغی",
            ts: 1585228579997,
          },
        },
      },
      person: 4,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            e: "to come / go over to (third person or place)",
            ec: "come,comes,coming,came,come",
            f: "wărtlul",
            g: "wartlul",
            noOo: true,
            p: "ورتلل",
            pprtf: "wărghúlay",
            pprtp: "ورغلی",
            prf: "wárghlul",
            prp: "ورغلل",
            psf: "wărdz",
            psp: "ورځ",
            r: 4,
            separationAtF: 3,
            separationAtP: 2,
            ssf: "wársh",
            ssp: "ورش",
            tppf: "wărghay",
            tppp: "ورغی",
            ts: 1585228579997,
          },
        },
      },
      person: 5,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            e: "to come / go over to (third person or place)",
            ec: "come,comes,coming,came,come",
            f: "wărtlul",
            g: "wartlul",
            noOo: true,
            p: "ورتلل",
            pprtf: "wărghúlay",
            pprtp: "ورغلی",
            prf: "wárghlul",
            prp: "ورغلل",
            psf: "wărdz",
            psp: "ورځ",
            r: 4,
            separationAtF: 3,
            separationAtP: 2,
            ssf: "wársh",
            ssp: "ورش",
            tppf: "wărghay",
            tppp: "ورغی",
            ts: 1585228579997,
          },
        },
      },
      person: 10,
      type: "VB",
    },
  ],
  [
    null,
    {
      info: {
        aspect: "perfective",
        base: "stem",
        type: "verb",
        verb: {
          entry: {
            c: "v. intrans.",
            e: "to come / go over to (third person or place)",
            ec: "come,comes,coming,came,come",
            f: "wărtlul",
            g: "wartlul",
            noOo: true,
            p: "ورتلل",
            pprtf: "wărghúlay",
            pprtp: "ورغلی",
            prf: "wárghlul",
            prp: "ورغلل",
            psf: "wărdz",
            psp: "ورځ",
            r: 4,
            separationAtF: 3,
            separationAtP: 2,
            ssf: "wársh",
            ssp: "ورش",
            tppf: "wărghay",
            tppp: "ورغی",
            ts: 1585228579997,
          },
        },
      },
      person: 11,
      type: "VB",
    },
  ],
];
