import * as T from "../../../types";

export const raatlul = {
  entry: {
    ts: 1527815216,
    i: 6926,
    p: "راتلل",
    f: "raatlúl",
    g: "raatlul",
    e: "to come",
    r: 4,
    c: "v. intrans.",
    psp: "راځ",
    psf: "raadz",
    ssp: "راش",
    ssf: "ráash",
    prp: "راغلل",
    prf: "ráaghlul",
    pprtp: "راغلی",
    pprtf: "raaghúlay",
    tppp: "راغی",
    tppf: "ráaghay",
    noOo: true,
    separationAtP: 2,
    separationAtF: 3,
    ec: "come,comes,coming,came,come",
  },
} as T.VerbEntry;

export const tlul = {
  entry: {
    ts: 1527815348,
    i: 3820,
    p: "تلل",
    f: "tlul",
    g: "tlul",
    e: "to go",
    r: 4,
    c: "v. intrans.",
    psp: "ځ",
    psf: "dz",
    ssp: "لاړ ش",
    ssf: "láaR sh",
    prp: "لاړل",
    prf: "láaRul",
    tppp: "لاړ",
    tppf: "laaR",
    separationAtP: 2,
    separationAtF: 3,
    ec: "go,goes,going,went,gone",
  },
} as T.VerbEntry;

export const wartlul = {
  entry: {
    ts: 1585228579997,
    i: 14924,
    p: "ورتلل",
    f: "wărtlul",
    g: "wartlul",
    e: "to come / go over to (third person or place)",
    r: 4,
    c: "v. intrans.",
    psp: "ورځ",
    psf: "wărdz",
    ssp: "ورش",
    ssf: "wársh",
    prp: "ورغلل",
    prf: "wárghlul",
    pprtp: "ورغلی",
    pprtf: "wărghúlay",
    tppp: "ورغی",
    tppf: "wărghay",
    noOo: true,
    separationAtP: 2,
    separationAtF: 3,
    ec: "come,comes,coming,came,come",
  },
} as T.VerbEntry;

export const dartlul = {
  entry: {
    ts: 1585228551150,
    i: 6320,
    p: "درتلل",
    f: "dărtlul",
    g: "dartlul",
    e: "to come (to you / second person)",
    r: 3,
    c: "v. intrans.",
    psp: "درځ",
    psf: "dărdz",
    ssp: "درش",
    ssf: "dársh",
    prp: "درغلل",
    prf: "dárghlul",
    pprtp: "درغلی",
    pprtf: "dărghúlay",
    tppp: "درغی",
    tppf: "dărghay",
    noOo: true,
    separationAtP: 2,
    separationAtF: 3,
    ec: "come,comes,coming,came,come",
  },
} as T.VerbEntry;

export const kedulStat = {
  entry: {
    ts: 1581086654898,
    i: 11100,
    p: "کېدل",
    f: "kedul",
    g: "kedul",
    e: "to become _____",
    r: 2,
    c: "v. intrans.",
    ssp: "ش",
    ssf: "sh",
    prp: "شول",
    prf: "shwul",
    pprtp: "شوی",
    pprtf: "shúway",
    noOo: true,
    ec: "become",
  },
} as T.VerbEntry;
export const kedulDyn = {
  entry: {
    ts: 1527812754,
    i: 11101,
    p: "کېدل",
    f: "kedul",
    g: "kedul",
    e: "to happen, occur",
    r: 2,
    c: "v. intrans.",
    ssp: "وش",
    ssf: "óosh",
    prp: "وشول",
    prf: "óoshwul",
    pprtp: "شوی",
    pprtf: "shúway",
    diacExcept: true,
    ec: "happen",
    separationAtP: 1,
    separationAtF: 2,
  },
} as T.VerbEntry;

export const kawulStat = {
  entry: {
    ts: 1579015359582,
    i: 11112,
    p: "کول",
    f: "kawul",
    g: "kawul",
    e: 'to make ____ ____ (as in "He\'s making me angry.")',
    r: 4,
    c: "v. trans.",
    ssp: "کړ",
    ssf: "kR",
    prp: "کړل",
    prf: "kRul",
    pprtp: "کړی",
    pprtf: "kúRay",
    noOo: true,
    ec: "make,makes,making,made,made",
  },
} as T.VerbEntry;

export const kawulDyn = {
  entry: {
    ts: 1527812752,
    i: 11113,
    p: "کول",
    f: "kawul",
    g: "kawul",
    e: "to do (an action or activity)",
    r: 4,
    c: "v. trans./gramm. trans.",
    ssp: "وکړ",
    ssf: "óokR",
    prp: "وکړل",
    prf: "óokRul",
    pprtp: "کړی",
    pprtf: "kúRay",
    separationAtP: 1,
    separationAtF: 2,
    diacExcept: true,
    ec: "do,does,doing,did,done",
  },
} as T.VerbEntry;
