import * as T from "../../types";

export const sandwiches: T.Sandwich[] = [
  {
    type: "sandwich",
    before: { p: "له", f: "la" },
    after: { p: "سره", f: "sara" },
    e: "with",
    mayo: false,
  },
  {
    type: "sandwich",
    before: undefined,
    after: { p: "ته", f: "ta" },
    e: "to",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "لپاره", f: "lapaara" },
    e: "for",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "دمخې", f: "dumúkhe" },
    e: "before/in front of",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "په څانګ", f: "pu tsaang" },
    e: "beside",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "پر", f: "pur" },
    after: { p: "باندې", f: "baande" },
    e: "on",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "په", f: "pu" },
    after: { p: "کې", f: "ke" },
    e: "in",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "دننه", f: "dununa" },
    e: "inside",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "دباندې", f: "dubaande" },
    e: "outside",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "مخې ته", f: "mukhe ta" },
    e: "in front of",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "شا ته", f: "shaa ta" },
    e: "behind",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "لاندې", f: "laande" },
    e: "under",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "په شان", f: "pu shaan" },
    e: "like",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "غوندې", f: "ghwunde" },
    e: "like",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "په حیث", f: "pu hays" },
    e: "as",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "په لور", f: "pu lor" },
    e: "towards",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "په اړه", f: "pu aRa" },
    e: "about",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "په باره کې", f: "pu baara ke" },
    e: "about",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "د", f: "du" },
    after: { p: "په اړوند", f: "pu aRwand" },
    e: "concerning",
    mayo: false,
  },
  {
    type: "sandwich",
    before: { p: "له", f: "la" },
    after: { p: "نه", f: "na" },
    e: "from",
    mayo: true,
  },
  {
    type: "sandwich",
    before: { p: "له", f: "la" },
    after: undefined,
    e: "from",
    mayo: true,
  },
  {
    type: "sandwich",
    before: { p: "له", f: "la" },
    after: { p: "څخه", f: "tsuxa" },
    e: "from",
    mayo: true,
  },
  {
    type: "sandwich",
    before: { p: "بې", f: "be" },
    after: undefined,
    e: "without",
    mayo: true,
  },
  {
    type: "sandwich",
    before: { p: "بې له", f: "be la" },
    after: undefined,
    e: "without",
    mayo: true,
  },
  {
    type: "sandwich",
    before: { p: "له", f: "la" },
    after: { p: "پرته", f: "práta" },
    e: "without",
    mayo: true,
  },
  {
    type: "sandwich",
    before: { p: "پرته له", f: "práta la" },
    after: undefined,
    e: "without",
    mayo: true,
  },
  {
    type: "sandwich",
    before: { p: "تر", f: "tur" },
    after: undefined,
    e: "until/up to",
    mayo: true,
  },
  {
    type: "sandwich",
    before: { p: "تر", f: "tur" },
    after: { p: "پورې", f: "póre" },
    e: "until/up to",
    mayo: true,
  },
];

export default sandwiches;
