name: CI

on:
  push:
    branches: [ 'master' ]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      LINGDOCS_DICTIONARY_URL: ${{ secrets.LINGDOCS_DICTIONARY_URL }}
      LINGDOCS_NPM_TOKEN: ${{ secrets.LINGDOCS_NPM_TOKEN }}
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish when version changed
        if: steps.check.outputs.changed == 'true'
        run: |
          yarn install
          yarn build-library
          yarn test
          npm publish