name: Publish

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      LINGDOCS_DICTIONARY_URL: ${{ secrets.LINGDOCS_DICTIONARY_URL }}
      LINGDOCS_NPM_TOKEN: ${{ secrets.LINGDOCS_NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish when version changed
        if: steps.check.outputs.changed == 'true'
        run: |
          yarn install-all
          yarn get-words
          yarn build-lib
          yarn build-components
          yarn test --silent
          cp .npmrc src/lib
          cp .npmrc src/components
          cd src/lib
          npm publish
          cd ../components
          npm publish
