name: "Test Nix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-23.05"
      - uses: workflow/nix-shell-action@v3
        with:
          packages: nodejs_20,pandoc
          script: |
            node --version
            pandoc --version
